name: Frontend CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build Docker image for Frontend
      run: docker build -t frontend-app ./frontend/medhead

    - name: Run Docker container to build Frontend
      run: docker run --rm frontend-app npm install && npm run build

    - name: Upload Frontend Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: frontend-build
        path: ./frontend/medhead/build/
